### PR TITLE
Add LICENSE file.

### PR DESCRIPTION
**Pull request by AdrianKoshka**
Might as well add a LICENSE file, just for having one's sake. Some people could be salty and say you need a LICENSE, this is to get them off your back :P

### CODE REVIEW

**Comment by alphapapa** [comment]
Aww, do I have to?  (I mean, I am a GPL advocate, but this is such a simple script...)  :)

**Comment by AdrianKoshka** [comment]
I wouldn't say you have to but some people(not to be rude, I understand where they come from) REALLY do want to be legally sure of what they're getting into :P so that's why I proposed this pr.

**Comment by alphapapa** [comment]
Thanks.  I'll meow it over.

**Comment by AdrianKoshka** [comment]
Thanks.

**Comment by alphapapa** [comment]
Don't worry, I haven't decided against it.  :)  I'm a big FOSS advocate, but when it comes to "software"  this simple, I think I'm even more of an "anyone could do that in 5 minutes, so it shouldn't even be copyrightable" advocate.

But I'm not necessarily opposed to applying the GPL, so I'll probably get around to it.  :)

**Comment by AdrianKoshka** [comment]
I know :P

**Pull request closed without merging**
